services:
  example:
    build: .
    tty: true
    privileged: true
    environment:
      ROS_DOMAIN_ID: 33
      ROS_LOCALHOST_ONLY: 0
    network_mode: host
    volumes:
      - .:/root/ros2_ws
    command: >
      /bin/bash -c "
      source /opt/ros/humble/setup.bash && /bin/bash"
