services:
  example:
    build: .
    tty: true
    privileged: true
    environment:
      - ROS_DOMAIN_ID=33
      # FASTRTPS_DEFAULT_PROFILES_FILE: /tmp/fastrtps-profile.xml
      - DISPLAY=$DISPLAY
    network_mode: host
    volumes:
      - .:/root/ros2_ws
      # - ./fastrtps-profile.xml:/tmp/fastrtps-profile.xml
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: >
      /bin/bash
