services:
  ros2-openpose:
    build: .
    tty: true
    privileged: true
    network_mode: host
    environment:
      # don't modify
      - DISPLAY=$DISPLAY

      # ROS2 settings
      - ROS_DOMAIN_ID=33

      # display settings
      - POSE_THRESHOLD=0.45
      - DISPLAY_SCALE=1.5

      # requester settings
      - PLEIADES_HOST=http://localhost/api/v0.5/
      - MAX_JOB=5
      - POSE_FPS=10
      # - DELAY=0.2 # for delayer
    volumes:
      - .:/root/ros2_ws

      # for GUI
      - /tmp/.X11-unix:/tmp/.X11-unix

      # for mDNS
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    working_dir: /root/ros2_ws
    command: >
      /bin/bash -c "
        source /opt/ros/humble/setup.bash &&
        colcon build --symlink-install &&
        source ./install/setup.bash &&
        # ros2 launch launcher without_camera.py
        # ros2 launch launcher with_camera.py
        ros2 launch launcher launch.py
        # ros2 launch launcher delay_launch.py
      "
