services:
  example:
    build: .
    tty: true
    privileged: true
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=33
      # FASTRTPS_DEFAULT_PROFILES_FILE: /tmp/fastrtps-profile.xml
      - DISPLAY=$DISPLAY
      # - PLEIADES_HOST=http://192.168.168.127:8332/api/v0.5/
      # - PLEIADES_HOST=http://192.168.64.150/api/v0.5/
      - PLEIADES_HOST=http://192.168.1.11/api/v0.5/
    volumes:
      - .:/root/ros2_ws
      # - ./fastrtps-profile.xml:/tmp/fastrtps-profile.xml
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /root/ros2_ws
    command: >
      /bin/bash -c "
        source /opt/ros/humble/setup.bash &&
        colcon build --symlink-install --packages-select pose &&
        source /root/ros2_ws/install/setup.bash &&
        ros2 launch pose launch.py
      "
