services:
  example:
    build: .
    tty: true
    privileged: true
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=33
      - FASTRTPS_DEFAULT_PROFILES_FILE=/tmp/fastrtps-profile.xml
      - DISPLAY=$DISPLAY
      # - PLEIADES_HOST=http://192.168.168.127:8332/api/v0.5/
      # - PLEIADES_HOST=http://tb3-sasaki.local/api/v0.5/
      # - PLEIADES_HOST=http://master.local/api/v0.5/
      - PLEIADES_HOST=http://pleiades.local/api/v0.5/
    volumes:
      - .:/root/ros2_ws
      - ./fastrtps-profile.xml:/tmp/fastrtps-profile.xml

      # for GUI
      - /tmp/.X11-unix:/tmp/.X11-unix

      # for mDNS
      - /var/run/dbus:/var/run/dbus 
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    working_dir: /root/ros2_ws
    command: >
      /bin/bash -c "
        source /opt/ros/humble/setup.bash &&
        colcon build --symlink-install &&
        source ./install/setup.bash &&
        ros2 launch launcher without_camera_launch.py
        # ros2 launch launcher launch.py
      "
