services:
  example:
    build: .
    tty: true
    privileged: true
    environment:
      ROS_DOMAIN_ID: 33
      ROS_LOCALHOST_ONLY: 0
    volumes:
      - .:/root/ros2_ws
    command: >
      /bin/bash
